# Generated by Django 3.2.13 on 2022-05-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_temp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='hour',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
